In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/playground-series-s4e4/sample_submission.csv
/kaggle/input/playground-series-s4e4/train.csv
/kaggle/input/playground-series-s4e4/test.csv
/kaggle/input/addition/abalone.data

In [2]:
sub = pd.read_csv('/kaggle/input/playground-series-s4e4/sample_submission.csv')
train = pd.read_csv('/kaggle/input/playground-series-s4e4/train.csv')
test = pd.read_csv('/kaggle/input/playground-series-s4e4/test.csv')
add = pd.read_csv('/kaggle/input/addition/abalone.data')

In [3]:
sub

           id  Rings
0       90615     10
1       90616     10
2       90617     10
3       90618     10
4       90619     10
...       ...    ...
60406  151021     10
60407  151022     10
60408  151023     10
60409  151024     10
60410  151025     10

[60411 rows x 2 columns]

In [4]:
train.columns

Index(['id', 'Sex', 'Length', 'Diameter', 'Height', 'Whole weight',
       'Whole weight.1', 'Whole weight.2', 'Shell weight', 'Rings'],
      dtype='object')

In [5]:

add.columns = ['Sex', 'Length', 'Diameter', 'Height', 'Whole weight',
       'Whole weight.1', 'Whole weight.2', 'Shell weight', 'Rings']

In [6]:
add

,Sex,Length,Diameter,Height,Whole weight,Whole weight.1,Whole weight.2,Shell weight,Rings
0,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7
1,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9
2,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10
3,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7
4,I,0.425,0.300,0.095,0.3515,0.1410,0.0775,0.1200,8
...,...,...,...,...,...,...,...,...,...
4171,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11
4172,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4173,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4174,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4175,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12

In [7]:
test

,id,Sex,Length,Diameter,Height,Whole weight,Whole weight.1,Whole weight.2,Shell weight
0,90615,M,0.645,0.475,0.155,1.2380,0.6185,0.3125,0.3005
1,90616,M,0.580,0.460,0.160,0.9830,0.4785,0.2195,0.2750
2,90617,M,0.560,0.420,0.140,0.8395,0.3525,0.1845,0.2405
3,90618,M,0.570,0.490,0.145,0.8740,0.3525,0.1865,0.2350
4,90619,I,0.415,0.325,0.110,0.3580,0.1575,0.0670,0.1050
...,...,...,...,...,...,...,...,...,...
60406,151021,I,0.345,0.260,0.085,0.1775,0.0735,0.0265,0.0500
60407,151022,F,0.525,0.410,0.145,0.8445,0.3885,0.1670,0.2050
60408,151023,I,0.590,0.440,0.155,1.1220,0.3930,0.2000,0.2650
60409,151024,F,0.660,0.525,0.190,1.4935,0.5885,0.3575,0.4350
60410,151025,F,0.430,0.340,0.120,0.4150,0.1525,0.0910,0.0905

In [8]:
train.head()

,id,Sex,Length,Diameter,Height,Whole weight,Whole weight.1,Whole weight.2,Shell weight,Rings
0,0,F,0.550,0.430,0.150,0.7715,0.3285,0.1465,0.2400,11
1,1,F,0.630,0.490,0.145,1.1300,0.4580,0.2765,0.3200,11
2,2,I,0.160,0.110,0.025,0.0210,0.0055,0.0030,0.0050,6
3,3,M,0.595,0.475,0.150,0.9145,0.3755,0.2055,0.2500,10
4,4,I,0.555,0.425,0.130,0.7820,0.3695,0.1600,0.1975,9

In [9]:
train = pd.concat([train , add])

In [10]:
train.shape

(94791, 10)

In [11]:
train.drop_duplicates(inplace = True)
train.shape

(94791, 10)

In [12]:
train.reset_index(inplace = True)

In [13]:
train.describe()

,index,id,Length,Diameter,Height,Whole weight,Whole weight.1,Whole weight.2,Shell weight,Rings
count,94791.000000,90615.000000,94791.000000,94791.000000,94791.000000,94791.000000,94791.000000,94791.000000,94791.000000,94791.000000
mean,43402.972909,45307.000000,0.517403,0.401953,0.135643,0.790788,0.341598,0.169915,0.226469,9.707177
std,27071.188699,26158.441658,0.118308,0.098088,0.038193,0.459233,0.205268,0.101334,0.130640,3.178674
min,0.000000,0.000000,0.075000,0.055000,0.000000,0.002000,0.001000,0.000500,0.001500,1.000000
25%,19521.500000,22653.500000,0.445000,0.345000,0.110000,0.419500,0.177500,0.086500,0.120000,8.000000
50%,43219.000000,45307.000000,0.545000,0.425000,0.140000,0.799500,0.330000,0.166000,0.225000,9.000000
75%,66916.500000,67960.500000,0.600000,0.470000,0.160000,1.072500,0.464500,0.233000,0.305000,11.000000
max,90614.000000,90614.000000,0.815000,0.650000,1.130000,2.825500,1.488000,0.760000,1.005000,29.000000

In [14]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 94791 entries, 0 to 94790
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   index           94791 non-null  int64
 1   id              90615 non-null  float64
 2   Sex             94791 non-null  object
 3   Length          94791 non-null  float64
 4   Diameter        94791 non-null  float64
 5   Height          94791 non-null  float64
 6   Whole weight    94791 non-null  float64
 7   Whole weight.1  94791 non-null  float64
 8   Whole weight.2  94791 non-null  float64
 9   Shell weight    94791 non-null  float64
 10  Rings           94791 non-null  int64
dtypes: float64(8), int64(2), object(1)
memory usage: 8.0+ MB

In [15]:
train.drop('id' ,axis = 1 , inplace = True)

In [16]:
train['Sex'].value_counts()

Sex
I    34435
M    32554
F    27802
Name: count, dtype: int64

In [17]:
corr_mat = train.drop('Sex' , axis = 1).corr()
corr_mat

,index,Length,Diameter,Height,Whole weight,Whole weight.1,Whole weight.2,Shell weight,Rings
index,1.000000,0.000626,-0.000133,-0.001611,-0.000850,-0.002017,-0.002771,-0.001144,-0.004286
Length,0.000626,1.000000,0.989600,0.911600,0.931092,0.908951,0.912522,0.910372,0.620828
Diameter,-0.000133,0.989600,1.000000,0.915263,0.933385,0.907634,0.913826,0.917211,0.634108
Height,-0.001611,0.911600,0.915263,1.000000,0.898077,0.857288,0.881600,0.899586,0.660500
Whole weight,-0.000850,0.931092,0.933385,0.898077,1.000000,0.971160,0.973909,0.963767,0.613687
Whole weight.1,-0.002017,0.908951,0.907634,0.857288,0.971160,1.000000,0.948351,0.910345,0.510616
Whole weight.2,-0.002771,0.912522,0.913826,0.881600,0.973909,0.948351,1.000000,0.935596,0.584925
Shell weight,-0.001144,0.910372,0.917211,0.899586,0.963767,0.910345,0.935596,1.000000,0.691632
Rings,-0.004286,0.620828,0.634108,0.660500,0.613687,0.510616,0.584925,0.691632,1.000000

In [18]:
train_df = pd.get_dummies(train, columns=['Sex'])  # Avoids multicollinearity

# Concatenate the encoded columns with the original DataFrame (excluding the original categorical column)
# df = pd.concat([train.drop('Sex', axis=1), encoded_df], axis=1)

train_df.head()

,index,Length,Diameter,Height,Whole weight,Whole weight.1,Whole weight.2,Shell weight,Rings,Sex_F,Sex_I,Sex_M
0,0,0.550,0.430,0.150,0.7715,0.3285,0.1465,0.2400,11,True,False,False
1,1,0.630,0.490,0.145,1.1300,0.4580,0.2765,0.3200,11,True,False,False
2,2,0.160,0.110,0.025,0.0210,0.0055,0.0030,0.0050,6,False,True,False
3,3,0.595,0.475,0.150,0.9145,0.3755,0.2055,0.2500,10,False,False,True
4,4,0.555,0.425,0.130,0.7820,0.3695,0.1600,0.1975,9,False,True,False

In [19]:
train_df[['Sex_F' , 'Sex_I' , 'Sex_M']] = train_df[['Sex_F' , 'Sex_I' , 'Sex_M']].astype(int)
train_df.head()

,index,Length,Diameter,Height,Whole weight,Whole weight.1,Whole weight.2,Shell weight,Rings,Sex_F,Sex_I,Sex_M
0,0,0.550,0.430,0.150,0.7715,0.3285,0.1465,0.2400,11,1,0,0
1,1,0.630,0.490,0.145,1.1300,0.4580,0.2765,0.3200,11,1,0,0
2,2,0.160,0.110,0.025,0.0210,0.0055,0.0030,0.0050,6,0,1,0
3,3,0.595,0.475,0.150,0.9145,0.3755,0.2055,0.2500,10,0,0,1
4,4,0.555,0.425,0.130,0.7820,0.3695,0.1600,0.1975,9,0,1,0

In [20]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 94791 entries, 0 to 94790
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   index           94791 non-null  int64
 1   Length          94791 non-null  float64
 2   Diameter        94791 non-null  float64
 3   Height          94791 non-null  float64
 4   Whole weight    94791 non-null  float64
 5   Whole weight.1  94791 non-null  float64
 6   Whole weight.2  94791 non-null  float64
 7   Shell weight    94791 non-null  float64
 8   Rings           94791 non-null  int64
 9   Sex_F           94791 non-null  int64
 10  Sex_I           94791 non-null  int64
 11  Sex_M           94791 non-null  int64
dtypes: float64(7), int64(5)
memory usage: 8.7 MB

In [21]:
train_df['new1'] = train_df['Shell weight'] / train_df['Whole weight']
train_df['new2'] = train_df['Whole weight.1'] / train_df['Whole weight']
train_df['new3'] = train_df['Whole weight.2'] / train_df['Whole weight']

In [22]:
train_df.corr()

,index,Length,Diameter,Height,Whole weight,Whole weight.1,Whole weight.2,Shell weight,Rings,Sex_F,Sex_I,Sex_M,new1,new2,new3
index,1.000000,0.000626,-0.000133,-0.001611,-0.000850,-0.002017,-0.002771,-0.001144,-0.004286,0.002232,0.001556,-0.003716,-0.003482,-0.007956,-0.006901
Length,0.000626,1.000000,0.989600,0.911600,0.931092,0.908951,0.912522,0.910372,0.620828,0.363098,-0.651897,0.312130,-0.162950,0.045586,-0.036223
Diameter,-0.000133,0.989600,1.000000,0.915263,0.933385,0.907634,0.913826,0.917211,0.634108,0.368469,-0.660473,0.315667,-0.149103,0.036245,-0.035657
Height,-0.001611,0.911600,0.915263,1.000000,0.898077,0.857288,0.881600,0.899586,0.660500,0.364169,-0.639279,0.298324,-0.091523,-0.012421,-0.017226
Whole weight,-0.000850,0.931092,0.933385,0.898077,1.000000,0.971160,0.973909,0.963767,0.613687,0.365690,-0.646892,0.304576,-0.179376,0.022051,-0.020367
Whole weight.1,-0.002017,0.908951,0.907634,0.857288,0.971160,1.000000,0.948351,0.910345,0.510616,0.339295,-0.614731,0.297309,-0.235631,0.173206,-0.015800
Whole weight.2,-0.002771,0.912522,0.913826,0.881600,0.973909,0.948351,1.000000,0.935596,0.584925,0.367840,-0.642271,0.297834,-0.178950,0.024738,0.137830
Shell weight,-0.001144,0.910372,0.917211,0.899586,0.963767,0.910345,0.935596,1.000000,0.691632,0.369054,-0.643497,0.297912,0.014611,-0.035806,-0.025245
Rings,-0.004286,0.620828,0.634108,0.660500,0.613687,0.510616,0.584925,0.691632,1.000000,0.294422,-0.513206,0.237505,0.139630,-0.193239,-0.055075
Sex_F,0.002232,0.363098,0.368469,0.364169,0.365690,0.339295,0.367840,0.369054,0.294422,1.000000,-0.486604,-0.465923,-0.021912,-0.037202,0.031517
Sex_I,0.001556,-0.651897,-0.660473,-0.639279,-0.646892,-0.614731,-0.642271,-0.643497,-0.513206,-0.486604,1.000000,-0.546283,0.061542,0.039820,-0.032617
Sex_M,-0.003716,0.312130,0.315667,0.298324,0.304576,0.297309,0.297834,0.297912,0.237505,-0.465923,-0.546283,1.000000,-0.041323,-0.004663,0.002818
new1,-0.003482,-0.162950,-0.149103,-0.091523,-0.179376,-0.235631,-0.178950,0.014611,0.139630,-0.021912,0.061542,-0.041323,1.000000,-0.106659,0.131143
new2,-0.007956,0.045586,0.036245,-0.012421,0.022051,0.173206,0.024738,-0.035806,-0.193239,-0.037202,0.039820,-0.004663,-0.106659,1.000000,0.059345
new3,-0.006901,-0.036223,-0.035657,-0.017226,-0.020367,-0.015800,0.137830,-0.025245,-0.055075,0.031517,-0.032617,0.002818,0.131143,0.059345,1.000000

In [23]:
X = train_df.drop(['index', 'Rings'] , axis = 1)
y = train_df['Rings']

In [24]:
df = pd.get_dummies(test, columns=['Sex'])
df[['Sex_F' , 'Sex_I' , 'Sex_M']] = df[['Sex_F' , 'Sex_I' , 'Sex_M']].astype(int)
X_test = df.drop(['id'] , axis = 1)
y_test = sub['Rings']

In [25]:
X_test['new1'] = X_test['Shell weight'] / X_test['Whole weight']
X_test['new2'] = X_test['Whole weight.1'] / X_test['Whole weight']
X_test['new3'] = X_test['Whole weight.2'] / X_test['Whole weight']

In [26]:
from sklearn.linear_model import LinearRegression

from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVC
from xgboost import XGBRegressor

from sklearn.ensemble import RandomForestClassifier
# model = RandomForestClassifier(n_estimators=20, random_state=42)
# model = SVC( kernel='linear')
# model = RandomForestRegressor(n_estimators=10,  random_state=42) 
model = LinearRegression()

model.fit(X, y)

LinearRegression()

In [27]:
# import tensorflow as tf
# from tensorflow import keras


# model = keras.Sequential([
#   keras.layers.Dense(64, activation='relu', input_shape=(13,)),  # Input layer with 10 features
#   keras.layers.Dense(32, activation='relu'), 
#    keras.layers.Dense(16, activation='relu'), 
#   keras.layers.Dense(1) 
# ])

# # Compile the model
# model.compile(optimizer='adam', loss='mse')  # Optimizer: Adam, Loss function: mean squared error

# model.fit(X, y, epochs=100, batch_size=32)

In [28]:
y_pred = model.predict(X)

In [29]:
y_pred = [max(x ,0) for x in y_pred]

In [30]:
from sklearn.metrics import mean_squared_log_error


rmsle = mean_squared_log_error(y, y_pred, squared=False)  
print("Root Mean Squared Logarithmic Error:", rmsle)

Root Mean Squared Logarithmic Error: 0.16454201737923682

In [31]:
test.shape

(60411, 9)

In [32]:
sub.head()

      id  Rings
0  90615     10
1  90616     10
2  90617     10
3  90618     10
4  90619     10

In [33]:
test_pred = model.predict(X_test)
test_pred = [max(x ,0) for x in test_pred]

In [34]:

rmsle = mean_squared_log_error(y_test, test_pred, squared=False)  
print("Root Mean Squared Logarithmic Error:", rmsle)

Root Mean Squared Logarithmic Error: 0.23872979161042135

In [35]:
submet = sub.copy()
sub

           id  Rings
0       90615     10
1       90616     10
2       90617     10
3       90618     10
4       90619     10
...       ...    ...
60406  151021     10
60407  151022     10
60408  151023     10
60409  151024     10
60410  151025     10

[60411 rows x 2 columns]

In [36]:
submet['Rings'] = test_pred

In [37]:
submet['Rings'] = submet['Rings'].astype(int)

In [38]:
submet.head()

      id  Rings
0  90615      8
1  90616     10
2  90617     10
3  90618     10
4  90619      7

In [39]:
submet.to_csv("/kaggle/working/df.csv", index=False, header=True)